# -*- coding: utf-8 -*-
"""Compatibility Scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vc4de3MM8eWf4HHy_SoGN_ow8aQhqYnX
"""

import pandas as pd
import numpy as np
import re
from pathlib import Path
import sys 

BATCH_DIR = Path(sys.argv[1])

# ======================================================
# 1. Load cleaned data
# ======================================================
mentors = pd.read_csv(BATCH_DIR / "mentors_clean.csv")
mentees = pd.read_csv(BATCH_DIR / "mentees_clean.csv")
S = pd.read_csv(BATCH_DIR / "field_similarity_matrix.csv", index_col=0)

# ======================================================
# 2. Parameters (i changed these)
# ======================================================
W_FIELD = 0.75
W_CAREER = 0.10
W_LOCATION = 0.08
W_COLLEGE = 0.04
W_ORG = 0.05      
SIM_THRESHOLD = 0.9
RHO = 1.5           # rank decay exponent
FIELD_FULL_MATCH_BOOST = 1.0
FIELD_NEAR_MATCH_BOOST = 0.9

# ======================================================
# 3. Helper functions
# ======================================================

def get_fields(row):
    """Return list of non-'None' fields for this mentor/mentee."""
    return [row[f"Field_{i}"] for i in range(1, 6)
            if str(row.get(f"Field_{i}", "")).strip() not in ["", "None", "nan", "NaN"]]

def rank_weights(n, rho=RHO):
    """Compute normalized rank weights (mentee-centric)."""
    ranks = np.arange(1, n + 1)
    w = 1 / (ranks ** rho)
    return (w / w.sum()).tolist()

def soft_jaccard_mentee(mentee_fields, mentor_fields):
    """Mentee-centric soft Jaccard using similarity matrix S."""
    if not mentee_fields or not mentor_fields:
        return 0
    weights = rank_weights(len(mentee_fields))
    total = 0
    for idx, f in enumerate(mentee_fields):
        if f in S.index:
            sim_scores = [S.loc[f, g] if g in S.columns else 0 for g in mentor_fields]
            total += weights[idx] * max(sim_scores)
    return total

def binary_overlap(list1, list2):
    """Return 1 if lists share at least one non-'None' element."""
    set1 = set(x.strip() for x in str(list1).split("|") if x.strip() not in ["None", ""])
    set2 = set(x.strip() for x in str(list2).split("|") if x.strip() not in ["None", ""])
    return int(len(set1 & set2) > 0)

def level_compatible(mentee_level, mentor_levels):
    """
    Return True if mentee's level is included in mentor's stated preferences.
    """
    if pd.isna(mentor_levels) or mentee_level in [None, "None", ""]:
        return True  # be permissive
    levels = [x.strip().lower() for x in str(mentor_levels).split(",")]
    return any(mentee_level.lower() in lvl for lvl in levels)

# ======================================================
# 4. Compatibility matrix computation
# ======================================================

comp_matrix = pd.DataFrame(0.0, index=mentees["Name"], columns=mentors["Name"])

for _, mnt_row in mentees.iterrows():
    mentee_name = mnt_row["Name"]
    mentee_level = str(mnt_row.get("Student_Level", "None"))
    mentee_fields = get_fields(mnt_row)

    for _, mtr_row in mentors.iterrows():
        mentor_name = mtr_row["Name"]
        mentor_fields = get_fields(mtr_row)

        # --------------------------------------------------
        # Field-of-interest compatibility (dominant feature)
        # --------------------------------------------------
        field_score = 0.0

        if mentee_fields and mentor_fields:
            # Top-1 exact match
            if mentee_fields[0] == mentor_fields[0]:
                field_score = W_FIELD * FIELD_FULL_MATCH_BOOST
            # Top-1 near match (similarity ≥ threshold)
            elif (mentee_fields[0] in S.index and mentor_fields[0] in S.columns and
                  S.loc[mentee_fields[0], mentor_fields[0]] >= SIM_THRESHOLD):
                field_score = W_FIELD * FIELD_NEAR_MATCH_BOOST
            else:
                # Smooth mentee-centric, rank-aware, similarity-aware matching
                field_score = W_FIELD * soft_jaccard_mentee(mentee_fields, mentor_fields)

        # --------------------------------------------------
        # Binary categorical matches
        # --------------------------------------------------
        career_match = binary_overlap(mnt_row["Career_Interests"], mtr_row["Career_Interests"])
        location_match = binary_overlap(mnt_row["Location"], mtr_row["Location"])
        college_match = binary_overlap(mnt_row["College"], mtr_row["College"])
        org_match = binary_overlap(mnt_row.get("Organization", ""), mtr_row.get("Organization", ""))

        # --------------------------------------------------
        # Combine weighted components
        # --------------------------------------------------
        total_score = (
            field_score +
            W_CAREER * career_match +
            W_LOCATION * location_match +
            W_COLLEGE * college_match +
            W_ORG * org_match
        )

        # --------------------------------------------------
        # Level compatibility filter (mentee-level vs mentor preferences)
        # --------------------------------------------------
        if not level_compatible(mentee_level, mtr_row.get("Mentor_Level_Preferences", "")):
            total_score = 0  # incompatible level

        # --------------------------------------------------
        # Cap at 1.0 and record
        # --------------------------------------------------
        comp_matrix.loc[mentee_name, mentor_name] = round(min(total_score, 1.0), 4)

# ======================================================
# 5. Save and summarize
# ======================================================

comp_matrix.to_csv(BATCH_DIR /"compatibility_matrix.csv" , index = True)
print("✅ Compatibility matrix saved as 'compatibility_matrix.csv'")
print(f"Shape: {comp_matrix.shape}")
print(f"Average compatibility: {comp_matrix.values.mean():.3f}")